# Generated by Django 4.2.2 on 2023-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("country_code", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("sources", models.CharField(max_length=100)),
                ("timezone", models.CharField(max_length=100)),
                ("station_id", models.CharField(max_length=100)),
                ("lon", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=100)),
                ("lat", models.CharField(max_length=100)),
                ("city_id", models.CharField(max_length=100)),
                ("json_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                ("datetime", models.BigIntegerField()),
                ("address_ip", models.GenericIPAddressField()),
                ("address_port", models.IntegerField()),
                ("original_message_id", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=10)),
                ("lat", models.FloatField()),
                ("lat_dir", models.CharField(max_length=10)),
                ("lon", models.FloatField()),
                ("lon_dir", models.CharField(max_length=10)),
                ("spd_over_grnd", models.FloatField()),
                ("true_course", models.FloatField()),
                ("datestamp", models.IntegerField()),
                ("mag_variation", models.FloatField()),
                ("mag_var_dir", models.CharField(max_length=10)),
                ("datetime_iso", models.DateTimeField()),
            ],
        ),
    ]
