# Generated by Django 4.2.2 on 2023-06-07 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="json_data",
            new_name="data",
        ),
    ]
