# Generated by Django 4.2.2 on 2023-06-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_json_data_location_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="data",
            field=models.JSONField(null=True),
        ),
    ]
