# Generated by Django 4.2.2 on 2023-06-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_location_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="data",
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pod", models.CharField(max_length=100)),
                ("pres", models.CharField(max_length=100)),
                ("azimuth", models.CharField(max_length=100)),
                ("clouds", models.CharField(max_length=100)),
                ("wind_spd", models.CharField(max_length=100)),
                ("h_angle", models.CharField(blank=True, max_length=100, null=True)),
                ("datetime", models.CharField(max_length=100)),
                ("timestamp_local", models.CharField(max_length=100)),
                ("precip", models.CharField(max_length=100)),
                ("timestamp_utc", models.CharField(max_length=100)),
                ("elev_angle", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=100)),
                ("vis", models.CharField(max_length=100)),
                ("uv", models.CharField(max_length=100)),
                ("temp", models.CharField(max_length=100)),
                ("dhi", models.CharField(max_length=100)),
                ("ghi", models.CharField(max_length=100)),
                ("dewpt", models.CharField(max_length=100)),
                ("wind_dir", models.CharField(max_length=100)),
                ("solar_rad", models.CharField(max_length=100)),
                ("rh", models.CharField(max_length=100)),
                ("slp", models.CharField(max_length=100)),
                ("snow", models.CharField(max_length=100)),
                ("ts", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.location",
                    ),
                ),
            ],
        ),
    ]
