# Generated by Django 4.2.2 on 2023-06-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_location_data_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.location",
            ),
        ),
    ]
