# Generated by Django 4.2.2 on 2023-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_data_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="h_angle",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
