# Generated by Django 4.2.2 on 2023-06-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_data_h_angle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="wind_spd",
            field=models.FloatField(),
        ),
    ]
