# Generated by Django 4.2.2 on 2023-06-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_data_wind_spd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="timestamp_utc",
            field=models.DateTimeField(),
        ),
    ]
