# Generated by Django 4.2.2 on 2023-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_data_timestamp_utc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="timestamp_utc",
            field=models.CharField(max_length=100),
        ),
    ]
